//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.22 at 01:28:36 PM IST 
//


package com.training.jaxb.customization.objects;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Double>
{


    public Double unmarshal(String value) {
        return (com.training.jaxb.CustomConverter.parseDecimal(value));
    }

    public String marshal(Double value) {
        return (com.training.jaxb.CustomConverter.printDecimal(value));
    }

}
