
package com.concept.ejb.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "InterestCalculatorService", targetNamespace = "http://webservice.ejb.concept.com/", wsdlLocation = "http://127.0.0.1:8080/EJBWebService/InterestCalculator?wsdl")
public class InterestCalculatorService
    extends Service
{

    private final static URL INTERESTCALCULATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.concept.ejb.webservice.InterestCalculatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.concept.ejb.webservice.InterestCalculatorService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/EJBWebService/InterestCalculator?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/EJBWebService/InterestCalculator?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTERESTCALCULATORSERVICE_WSDL_LOCATION = url;
    }

    public InterestCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterestCalculatorService() {
        super(INTERESTCALCULATORSERVICE_WSDL_LOCATION, new QName("http://webservice.ejb.concept.com/", "InterestCalculatorService"));
    }

    /**
     * 
     * @return
     *     returns InterestCalculator
     */
    @WebEndpoint(name = "InterestCalculatorPort")
    public InterestCalculator getInterestCalculatorPort() {
        return super.getPort(new QName("http://webservice.ejb.concept.com/", "InterestCalculatorPort"), InterestCalculator.class);
    }

}
