
package com.concept.ejb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "InterestCalculator", targetNamespace = "http://webservice.ejb.concept.com/")
public interface InterestCalculator {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateSimpleInterest", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterest")
    @ResponseWrapper(localName = "calculateSimpleInterestResponse", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterestResponse")
    public double calculateSimpleInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
