//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 05:28:41 PM IST 
//


package ch.e3ag.tgrid.corba._2013._03;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CS_B__Ex_T complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CS_B__Ex_T">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="d" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.e3ag.ch/tgrid/corba/2013/03}CS_B__ExDescr_T">
 *                 &lt;attGroup ref="{http://www.e3ag.ch/tgrid/corba/2013/03}TAttributeSequence1D"/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="t" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.e3ag.ch/tgrid/corba/2013/03}CS_B__ExTraceEntry_T">
 *                 &lt;attGroup ref="{http://www.e3ag.ch/tgrid/corba/2013/03}TAttributeSequence1D"/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CS_B__Ex_T", propOrder = {
    "d",
    "t"
})
public class CSBExT {

    protected List<CSBExT.D> d;
    protected List<CSBExT.T> t;

    /**
     * Gets the value of the d property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the d property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CSBExT.D }
     * 
     * 
     */
    public List<CSBExT.D> getD() {
        if (d == null) {
            d = new ArrayList<CSBExT.D>();
        }
        return this.d;
    }

    /**
     * Gets the value of the t property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the t property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CSBExT.T }
     * 
     * 
     */
    public List<CSBExT.T> getT() {
        if (t == null) {
            t = new ArrayList<CSBExT.T>();
        }
        return this.t;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.e3ag.ch/tgrid/corba/2013/03}CS_B__ExDescr_T">
     *       &lt;attGroup ref="{http://www.e3ag.ch/tgrid/corba/2013/03}TAttributeSequence1D"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class D
        extends CSBExDescrT
    {

        @XmlAttribute(required = true)
        protected String index;
        @XmlAttribute(required = true)
        protected TEnumSequenceType sequenceType;

        /**
         * Gets the value of the index property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndex(String value) {
            this.index = value;
        }

        /**
         * Gets the value of the sequenceType property.
         * 
         * @return
         *     possible object is
         *     {@link TEnumSequenceType }
         *     
         */
        public TEnumSequenceType getSequenceType() {
            return sequenceType;
        }

        /**
         * Sets the value of the sequenceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnumSequenceType }
         *     
         */
        public void setSequenceType(TEnumSequenceType value) {
            this.sequenceType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.e3ag.ch/tgrid/corba/2013/03}CS_B__ExTraceEntry_T">
     *       &lt;attGroup ref="{http://www.e3ag.ch/tgrid/corba/2013/03}TAttributeSequence1D"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class T
        extends CSBExTraceEntryT
    {

        @XmlAttribute(required = true)
        protected String index;
        @XmlAttribute(required = true)
        protected TEnumSequenceType sequenceType;

        /**
         * Gets the value of the index property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndex(String value) {
            this.index = value;
        }

        /**
         * Gets the value of the sequenceType property.
         * 
         * @return
         *     possible object is
         *     {@link TEnumSequenceType }
         *     
         */
        public TEnumSequenceType getSequenceType() {
            return sequenceType;
        }

        /**
         * Sets the value of the sequenceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnumSequenceType }
         *     
         */
        public void setSequenceType(TEnumSequenceType value) {
            this.sequenceType = value;
        }

    }

}
