//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 05:28:41 PM IST 
//


package ch.e3ag.tgrid.corba._2013._03;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.e3ag.tgrid.corba._2013._03 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.e3ag.tgrid.corba._2013._03
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CSBExTraceEntryT.Pgm }
     * 
     */
    public CSBExTraceEntryT.Pgm createCSBExTraceEntryTPgm() {
        return new CSBExTraceEntryT.Pgm();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderInT.OrderId }
     * 
     */
    public UpdateSavasCollectionOrderInT.OrderId createUpdateSavasCollectionOrderInTOrderId() {
        return new UpdateSavasCollectionOrderInT.OrderId();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderInT.LastModifiedTS }
     * 
     */
    public UpdateSavasCollectionOrderInT.LastModifiedTS createUpdateSavasCollectionOrderInTLastModifiedTS() {
        return new UpdateSavasCollectionOrderInT.LastModifiedTS();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT.BusEx }
     * 
     */
    public UpdateSavasCollectionOrderOutT.BusEx createUpdateSavasCollectionOrderOutTBusEx() {
        return new UpdateSavasCollectionOrderOutT.BusEx();
    }

    /**
     * Create an instance of {@link CSBHeaderT.UserLangCd }
     * 
     */
    public CSBHeaderT.UserLangCd createCSBHeaderTUserLangCd() {
        return new CSBHeaderT.UserLangCd();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT.LastModifiedTS }
     * 
     */
    public UpdateSavasCollectionOrderOutT.LastModifiedTS createUpdateSavasCollectionOrderOutTLastModifiedTS() {
        return new UpdateSavasCollectionOrderOutT.LastModifiedTS();
    }

    /**
     * Create an instance of {@link Corbares }
     * 
     */
    public Corbares createCorbares() {
        return new Corbares();
    }

    /**
     * Create an instance of {@link CSBExDescrT.Cd }
     * 
     */
    public CSBExDescrT.Cd createCSBExDescrTCd() {
        return new CSBExDescrT.Cd();
    }

    /**
     * Create an instance of {@link Corbares.ReturnValue }
     * 
     */
    public Corbares.ReturnValue createCorbaresReturnValue() {
        return new Corbares.ReturnValue();
    }

    /**
     * Create an instance of {@link CSBHeaderT }
     * 
     */
    public CSBHeaderT createCSBHeaderT() {
        return new CSBHeaderT();
    }

    /**
     * Create an instance of {@link CSBHeaderT.TraceLevel }
     * 
     */
    public CSBHeaderT.TraceLevel createCSBHeaderTTraceLevel() {
        return new CSBHeaderT.TraceLevel();
    }

    /**
     * Create an instance of {@link CSBExDescrT.Ctx }
     * 
     */
    public CSBExDescrT.Ctx createCSBExDescrTCtx() {
        return new CSBExDescrT.Ctx();
    }

    /**
     * Create an instance of {@link CSBExT.D }
     * 
     */
    public CSBExT.D createCSBExTD() {
        return new CSBExT.D();
    }

    /**
     * Create an instance of {@link Corbaparam }
     * 
     */
    public Corbaparam createCorbaparam() {
        return new Corbaparam();
    }

    /**
     * Create an instance of {@link CSBExDescrT }
     * 
     */
    public CSBExDescrT createCSBExDescrT() {
        return new CSBExDescrT();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT }
     * 
     */
    public UpdateSavasCollectionOrderOutT createUpdateSavasCollectionOrderOutT() {
        return new UpdateSavasCollectionOrderOutT();
    }

    /**
     * Create an instance of {@link CSBExTraceEntryT.Id }
     * 
     */
    public CSBExTraceEntryT.Id createCSBExTraceEntryTId() {
        return new CSBExTraceEntryT.Id();
    }

    /**
     * Create an instance of {@link Corbares.SysEx }
     * 
     */
    public Corbares.SysEx createCorbaresSysEx() {
        return new Corbares.SysEx();
    }

    /**
     * Create an instance of {@link Corbares.OutParam }
     * 
     */
    public Corbares.OutParam createCorbaresOutParam() {
        return new Corbares.OutParam();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT.Remarks }
     * 
     */
    public UpdateSavasCollectionOrderOutT.Remarks createUpdateSavasCollectionOrderOutTRemarks() {
        return new UpdateSavasCollectionOrderOutT.Remarks();
    }

    /**
     * Create an instance of {@link CSBExDescrT.Timestamp }
     * 
     */
    public CSBExDescrT.Timestamp createCSBExDescrTTimestamp() {
        return new CSBExDescrT.Timestamp();
    }

    /**
     * Create an instance of {@link CSBHeaderT.Empty }
     * 
     */
    public CSBHeaderT.Empty createCSBHeaderTEmpty() {
        return new CSBHeaderT.Empty();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderInT.SetOrderToState }
     * 
     */
    public UpdateSavasCollectionOrderInT.SetOrderToState createUpdateSavasCollectionOrderInTSetOrderToState() {
        return new UpdateSavasCollectionOrderInT.SetOrderToState();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT.OrderStatus }
     * 
     */
    public UpdateSavasCollectionOrderOutT.OrderStatus createUpdateSavasCollectionOrderOutTOrderStatus() {
        return new UpdateSavasCollectionOrderOutT.OrderStatus();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderInT }
     * 
     */
    public UpdateSavasCollectionOrderInT createUpdateSavasCollectionOrderInT() {
        return new UpdateSavasCollectionOrderInT();
    }

    /**
     * Create an instance of {@link UpdateSavasCollectionOrderOutT.OrderId }
     * 
     */
    public UpdateSavasCollectionOrderOutT.OrderId createUpdateSavasCollectionOrderOutTOrderId() {
        return new UpdateSavasCollectionOrderOutT.OrderId();
    }

    /**
     * Create an instance of {@link CSBExT }
     * 
     */
    public CSBExT createCSBExT() {
        return new CSBExT();
    }

    /**
     * Create an instance of {@link CSBExT.T }
     * 
     */
    public CSBExT.T createCSBExTT() {
        return new CSBExT.T();
    }

    /**
     * Create an instance of {@link CSBExTraceEntryT }
     * 
     */
    public CSBExTraceEntryT createCSBExTraceEntryT() {
        return new CSBExTraceEntryT();
    }

    /**
     * Create an instance of {@link CSBExDescrT.Params }
     * 
     */
    public CSBExDescrT.Params createCSBExDescrTParams() {
        return new CSBExDescrT.Params();
    }

    /**
     * Create an instance of {@link CSBHeaderT.ClientId }
     * 
     */
    public CSBHeaderT.ClientId createCSBHeaderTClientId() {
        return new CSBHeaderT.ClientId();
    }

}
