package com.concept.ejb.webservice;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 07 17:22:40 IST 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.ejb.concept.com/", name = "InterestCalculator")
@XmlSeeAlso({ObjectFactory.class})
public interface InterestCalculator {

    @RequestWrapper(localName = "calculateSimpleInterest", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterest")
    @ResponseWrapper(localName = "calculateSimpleInterestResponse", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterestResponse")
    @WebMethod(operationName = "calculateSimpleInterest")
    public Response<com.concept.ejb.webservice.CalculateSimpleInterestResponse> calculateSimpleInterestAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @RequestWrapper(localName = "calculateSimpleInterest", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterest")
    @ResponseWrapper(localName = "calculateSimpleInterestResponse", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterestResponse")
    @WebMethod(operationName = "calculateSimpleInterest")
    public Future<?> calculateSimpleInterestAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.concept.ejb.webservice.CalculateSimpleInterestResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateSimpleInterest", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterest")
    @WebMethod
    @ResponseWrapper(localName = "calculateSimpleInterestResponse", targetNamespace = "http://webservice.ejb.concept.com/", className = "com.concept.ejb.webservice.CalculateSimpleInterestResponse")
    public double calculateSimpleInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );
}
