
/*
 * 
 */

package com.concept.ejb.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Fri Dec 07 17:22:40 IST 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "InterestCalculatorService", 
                  wsdlLocation = "http://localhost:8080/EJBWebService/InterestCalculator?wsdl",
                  targetNamespace = "http://webservice.ejb.concept.com/") 
public class InterestCalculatorService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.ejb.concept.com/", "InterestCalculatorService");
    public final static QName InterestCalculatorPort = new QName("http://webservice.ejb.concept.com/", "InterestCalculatorPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EJBWebService/InterestCalculator?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/EJBWebService/InterestCalculator?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InterestCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterestCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterestCalculatorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InterestCalculatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public InterestCalculatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterestCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterestCalculator
     */
    @WebEndpoint(name = "InterestCalculatorPort")
    public InterestCalculator getInterestCalculatorPort() {
        return super.getPort(InterestCalculatorPort, InterestCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterestCalculator
     */
    @WebEndpoint(name = "InterestCalculatorPort")
    public InterestCalculator getInterestCalculatorPort(WebServiceFeature... features) {
        return super.getPort(InterestCalculatorPort, InterestCalculator.class, features);
    }

}
